Traceback (most recent call last):
  File "/home/user/webapp/start_mock_zap.py", line 116, in <module>
    start_mock_zap()
  File "/home/user/webapp/start_mock_zap.py", line 110, in start_mock_zap
    server = HTTPServer(('localhost', 8080), MockZAPHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
