INFO:     Started server process [3627]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3627]
INFO:     Started server process [4737]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [4737]
INFO:     Started server process [6042]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6042]
INFO:     Started server process [8491]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/anyio/_core/_eventloop.py", line 162, in get_async_backend
KeyError: 'asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/routing.py", line 462, in handle
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/staticfiles.py", line 94, in __call__
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/starlette/staticfiles.py", line 193, in check_config
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
  File "/home/user/webapp/test_env/lib/python3.12/site-packages/anyio/_core/_eventloop.py", line 164, in get_async_backend
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'anyio._backends'
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [8491]
INFO:     Started server process [9057]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [9057]
INFO:     Started server process [9994]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [9994]
INFO:     Started server process [10254]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
